[package]
name = "billionrow"
version = "0.1.0"
edition = "2024"
[profile.release]
panic = "abort"
lto = "fat"
debug = true
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]
[dependencies]
libc = "0.2.178"
